### ISSUE TITLE
Spaces in the user directory name or working directory name cause failure to establish connection with BBj or failure to launch BBj program

### ISSUE THREAD

**Issue by mphelpsbasis** [BBx-Kitchen/bbj-language-server#218]
EXAMPLE #1
Running VSCode on Windows, where the user directory is unfortunately C:/Users/Mike Phelps:
The VSCode BBj Language Support extension reports:

**BBj Error
Thin Client server on port 53919 failed to accept connection, returned error msg: Duplicate switch: multiple program names
(Phelps\.vscode\extensions\beu.bbj-vscode-0.0.31\java-interop,c:\Users\Mike)
VSCODE OUTPUT view:
Failed to connect to the Java service. Error: connect ECONNREFUSED 127.0.0.1:5008
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5008
}
Error: connect ECONNREFUSED 127.0.0.1:5008
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5008
}**

The 'props' properties assembled by .vscode/extensions/beu.bbj-vscode-0.0.33/java-interop/java-interop.bbj and delivered to BBj includes directory names truncated and mangled by the presence of a space character, like the following:
**Env.33=PROMPT=$P$G, Argv.4=c:\Users\Mike,
Env.39=SystemRoot=C:\Windows, Argv.2=-WDc:\Users\Mike, 
Env.38=SystemDrive=C:, Argv.5=Phelps\.vscode\extensions\beu.bbj-vscode-0.0.31\java-interop/java-interop.bbj, 
Env.36=SESSIONNAME=Console, Argv.3=Phelps\.vscode\extensions\beu.bbj-vscode-0.0.31\java-interop, 
Env.41=TMP=C:\Users\MIKEPH~1\AppData\Local\Temp, 
Env.40=TEMP=C:\Users\MIKEPH~1\AppData\Local\Temp,** 

As a result, the connection to BBj is never established and code completion reflection is not provided.  We assume that the string properties assembled by java-interop.bbj need to be quoted to handle embedded spaces.

EXAMPLE #2
Running VSCode on Mac, where the workspace program directory is Standard Insurance Project:

The VSCode BBj Language Support extension displays a popup window which reports:
**Failed to run "/Users/bryanhighhill/Downloads/Standard Insurance Project/test.bbj**

The debug.log file reports:
**"Exception(!ERROR=206) in ThinClientProxyServer:/[127.0.0.1:0](http://127.0.0.1:0/) [/[127.0.0.1:58505](http://127.0.0.1:58505/)] at Mon Dec 16 10:11:33 MST 2024:
com.basis.startup.type.BBjException: Duplicate switch: multiple program names (Insurance,Project)
at com.basis.bbj.client.util.CmdLineOptions.initialize(CmdLineOptions.java:297)
at com.basis.bbj.client.util.CmdLineOptions.<init>(CmdLineOptions.java:125)
at com.basis.bbj.client.util.CmdLineOptions.<init>(CmdLineOptions.java:304)
at com.basis.bbj.client.comm.ThinClientImpl.createProxyClient(ThinClientImpl.java:230)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at com.basis.startup.ThinClient.a(ThinClient.java:27)
at com.basis.bbj.client.comm.NettyThinClientProxyService$HandshakeDecoder.lambda$decode$1(NettyThinClientProxyService.java:77)
at com.basis.util.common.netty.RenameThreadRunnable.run(RenameThreadRunnable.java:6)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
[10:11:34.021-0700] INFO    ThinClientProxyServer:/[127.0.0.1:0](http://127.0.0.1:0/) [/[127.0.0.1:58505](http://127.0.0.1:58505/)] closed socket connection (0 total connections)"**

As a result, the CUI auto-launcher won't launch the BBj application.  However, the BUI launcher _does_ work.

**Comment by StephanWald** [comment]
Please do a complete retest on a system where BBj runs in something like C:/Program FIles or something else with a space.

**Comment by ckochaneck** [comment]
Pull Request: https://github.com/BBx-Kitchen/bbj-language-server/pull/280

**Comment by danielschick** [comment]
..would be great if this was merged..

**Comment by StephanWald** [comment]
target release 0.4.4

**Comment by StephanWald** [comment]
fixed in 0.4.4
